#!/bin/bash
# This hook is sourced after every virtualenv is activated.

# envs
export PROJECT_NAME=`basename $VIRTUAL_ENV`
export PROJECT_PATH=$PROJECT_HOME/$PROJECT_NAME
export DOTENV_DEFAULT_PATH=$PROJECT_HOME/$PROJECT_NAME/.env.default
export DOTENV_PATH=$PROJECT_HOME/$PROJECT_NAME/.env
export DJANGO_MANAGE_PATH=$PROJECT_HOME/$PROJECT_NAME/manage.py
export PACKAGE_JSON_DIR=$PROJECT_HOME/$PROJECT_NAME
export PIPFILE_DIR=$PROJECT_HOME/$PROJECT_NAME

echo "### Load $PROJECT_NAME virtualenv ###"

# Load .env.default
if [ -e $DOTENV_DEFAULT_PATH ]
then
  echo "### Load .env.default from $DOTENV_DEFAULT_PATH ###"
  set -a
  . $DOTENV_DEFAULT_PATH
  set +a
fi

# Load .env, will override .env.default
if [ -e $DOTENV_PATH ]
then
  echo "### Load .env from $DOTENV_PATH ###"
  set -a
  . $DOTENV_PATH
  set +a
fi

# aliases
echo "### Load aliases ###"
source $WORKON_HOME/scripts/django.sh && echo "* django loaded"
source $WORKON_HOME/scripts/pipenv.sh && echo "* pipenv loaded"
source $WORKON_HOME/scripts/docker.sh && echo "* docker loaded"
source $WORKON_HOME/scripts/postgresql.sh && echo "* postgres loaded"

