#!/bin/bash
# This hook is sourced after every virtualenv is activated.

# envs
export PROJECT_NAME=`basename $VIRTUAL_ENV`
export PROJECT_PATH=$PROJECT_HOME/$PROJECT_NAME
export DOTENV_PROJECT_PATH=$PROJECT_HOME/$PROJECT_NAME/.env.proj
export DOTENV_PATH=$PROJECT_HOME/$PROJECT_NAME/.env
export DJANGO_MANAGE_PATH=$PROJECT_HOME/$PROJECT_NAME/manage.py
export PACKAGE_JSON_DIR=$PROJECT_HOME/$PROJECT_NAME
export PIPFILE_DIR=$PROJECT_HOME/$PROJECT_NAME

echo "### Load $PROJECT_NAME virtualenv ###"

# Load .env.proj
if [ -e $DOTENV_PROJECT_PATH ]
then
  echo "### Load .env.proj from $DOTENV_PROJECT_PATH ###"
  set -a
  . $DOTENV_PROJECT_PATH
  set +a
fi

# Load .env, should ovveride .env.proj
if [ -e $DOTENV_PATH ]
then
  echo "### Load .env from $DOTENV_PATH ###"
  set -a
  . $DOTENV_PATH
  set +a
fi

# aliases
echo "### Load aliases ###"
source $WORKON_HOME/scripts/django.sh && echo "* django loaded"
source $WORKON_HOME/scripts/pipenv.sh && echo "* pipenv loaded"
source $WORKON_HOME/scripts/docker.sh && echo "* docker loaded"

